name = "aibridge-cloudflare"
main = "dist/index.mjs"           # or "cloudflare.ts" if compiled to .mjs at build
compatibility_date = "2023-08-01"

# Optional: environment variables you want to pass to your worker
# [vars]
# API_KEY = "some-secret"
# BASE_URL = "https://api.deepseek.com"
